project:
  type: website
  output-dir: docs

website:
  title: "MAT 337 Notes"
  navbar:
    left:
      - href: index.qmd
        text: Home
  sidebar:
    style: "floating"
    search: false
    contents:
      - section: other-courses.qmd
        contents:
          - csc303.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



